
services:
  master:
    image: ohm/locust
    build:
      context: .
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/muni_huam.py --master -H http://master:8089

  worker:
    image: ohm/locust
    build:
      context: .
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/muni_huam.py --worker --master-host master

